export const routes = {
    root: '/',
    homepage: '/homepage',
    investorInformation: '/investores/investor-information',
    annualGeneralMeeting: '/investores/annual-general-meeting',
    financial: '/investores/financials',
    markets: '/investores/markets',
    technicalReports: '/investores/technical-reports',
    archivedNewsReleases: '/investores/press-releases/archived-news-releases',
    latestNewReleases: '/investores/press-releases/latest-news-releases',
    investorLithiumArticles: '/investores/press-releases/lithium-articles',
    projects: '/projects',
    teelsMarsh: '/projects/teels-marsh',
    alkaliLake: '/projects/alkali-lake',
    guayatoyoc: '/projects/guayatoyoc',
    // foxCreek:'/projects/fox-creek',
    theLithiumMarket: '/lithium/the-lithium-market',
    supplyAndDemand: '/lithium/supply-and-demand',
    lithiumProducts: '/lithium/lithium-products',
    globalLithiumReserves: '/lithium/global-lithium-reserves',
    lithiumArticles: '/lithium/lithium-articles',
    videoGallery: '/lithium/video-gallery',
    lithiumTechnology: '/lithium/lithium-technology',
    lithiumRevolution: '/lithium/lithium-revolution',
    contact: '/contact',
    managementTeam: '/about/management-team',
    corporateRespinsibility: '/about/coporate-responsibility',
    login: '/login',
    dashboard:'/dashboard'
}